name: Changelog

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Changelog
    
    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          prerelease: false
